### ISSUE TITLE
The app refuses to run

### ISSUE THREAD

**Issue by techana** [eglooca/app-kimchi#3]
I'm running ClearOS Community 7.4 server. I've already installed KVM as per: https://www.clearos.com/resources/documentation/clearos/content:en_us:kb_7_install_virtualization_using_kvm

Then, I installed the app-kimchi ver. 1.1.8-1 as described here: http://wikisuite.org/How-to-install-Kimchi-on-ClearOS

The app refuses to run from the ClearOS webconfig (Status Stopped). The messages log doesn't give much in order to identify the problem.

**Comment by techana** [comment]
I reinstalled the whole ClearOS system then installed app-kimchi. The app's status in webconfig is now running, but when accessing its control panel I only see "Wok" (red theme) and no "Virtualization" tab. I'm sure my system supports KVM (because I can install and run virtual machines from CLI).

Here is /var/log/wok/wok-error.log when the app is started:
`*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Loading YumUpdate features.
System Update Tool ...: True
Repo Management Tool .: yum
*** Ginger Base: Capabilities tests completed ***

*** Kimchi: Running feature tests ***
Service Libvirtd running ...: True
operation failed: no storage pools were found on host '127.0.0.1'
NFS Target Probe support ...: True
Fibre Channel Host support .: True
Kernel VFIO support ........: True
Network Manager running ....: False
Memory Hotplug support .....: False
*** Kimchi: Feature tests completed ***

Unknown device type: drm
Fatal: Unable to activate network default.
Details: internal error: Child process (VIR_BRIDGE_NAME=virbr0 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper) unexpected exit status 2: 
dnsmasq: failed to bind DHCP server socket: Address already in use

Failed to import plugin plugins.kimchi.Kimchi, error: Network default does not exist or is not active. Please, check the configuration in /etc/kimchi/template.conf to ensure it lists only valid networks.
[06/Dec/2017:18:50:07] ENGINE Listening for SIGHUP.
[06/Dec/2017:18:50:07] ENGINE Listening for SIGTERM.
[06/Dec/2017:18:50:07] ENGINE Listening for SIGUSR1.
[06/Dec/2017:18:50:07] ENGINE Bus STARTING
[06/Dec/2017:18:50:07] ENGINE Serving on 127.0.0.1:8010

*** Kimchi: Running dependable feature tests ***
[06/Dec/2017:18:50:07] ENGINE Started monitor thread 'Session cleanup'.
QEMU stream support .......: False
Libvirt Stream Protocols ..: ['http', 'https', 'ftp', 'ftps', 'tftp']
*** Kimchi: Dependable feature tests completed ***

[06/Dec/2017:18:50:08] ENGINE Bus STARTED`

**Comment by techana** [comment]
Ok, I was able to solve this issue by solving the conflict between ClearOS' dnsmasq and Libvirtd's dnsmasq as explained here: https://wiki.libvirt.org/page/Libvirtd_and_dnsmasq. "Virtualization" tab appears in Kimchi control panel. But I'm not sure how this solution will affect ClearOS. I think it will prevent me from adding more NICs in the future!

I also had to change the Libvirtd default storage pool name to "images" in /etc/kimchi/template.conf.

**Comment by marclaporte** [comment]
@techana Thank you for reporting this.

Please do add feature requests with an explanation of the desired use case. We want to make it easy to set up without any manual configs. We can add options / setting in the app.

You can add here in the Kimchi category:
http://wikisuite.org/To-do

And it will appear here:
http://wikisuite.org/Kimchi-and-KVM-development

**Comment by techana** [comment]
Done. See here please: http://wikisuite.org/item259?from=To+do
